{{- if .Values.settingsPy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "hello-django.fullname" .) }}
  labels:
    {{- include "hello-django.labels" . | nindent 4 }}
type: Opaque
data:
  settings.py: |-
    {{ tpl ( .Files.Get "files/settings" )  . | b64enc }}
{{- end }}