{{- if .Values.configMap.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "app-guto.fullname" . }}
  labels:
    {{- include "app-guto.labels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}